Feature/1
darmadevZone/android-practice pull request #32
Opened 2024-04-15 03:21 UTC by darmadevZone

## 修正内容
issue: #1 

Resolve #1 

- 今回は、作成済みのコードを利用しました。
- キャッシュを生成するファイルの追加https://github.com/darmadevZone/android-practice/compare/feature/1?expand=1#diff-72a67638301d4444bbf665795baabd62075bce1edeb4b58ac63d767af367422d
- prをチェックするファイルの追加https://github.com/darmadevZone/android-practice/commit/3ea8e3916a0483b5bf923657223da3f6bd11d348
- [dangerfileの追加](https://github.com/darmadevZone/android-practice/commit/0a125506c03082f8401e70e909059948d9af3c85)
- [gemfileの追加](https://github.com/darmadevZone/android-practice/commit/7fba49b49391de1b43c01fb9d234300ab33e1359)
- [testRunnerとdistributionTypeの追加](https://github.com/darmadevZone/android-practice/commit/3c8836c9ec6df4ef9bf10fb39169ede3c139abf4)

## レビューレベルの設定

- [ ] まったく見ないでApproveする(基本的には非推奨。)
- [x] ぱっとみて違和感がないかチェックしてApproveする
- [ ] 仕様レベルまで理解して、仕様通りに動くかある程度検証、動作確認までしてApproveする
- [ ] その他 (以下にコメント記載)

## レビュー観点

## スクリーンショット

なし

## 備考

2024-04-15 23:59 UTC, askldfghj requested changes

2024-04-15 23:59 UTC, askldfghj commented on .github/actions/workflows/Dangerfile
@darmadevZone 
対応ありがとうござます。

> 2. .github/actions/check-pull-request/以下のファイルすべてを.github/workflows/以下に移動してくださいz

他のファイルも同じですが、
.github/actions/workflows ではなく、 .github/workflows/ に移動になります。
確認お願いします。

2024-04-16 01:11 UTC, penuwo commented
5e1dea5a7d892ae28153a0eaf2293e58a3cc141c こちらも本PRに含まれていたほうが良さそうに思いました（今回は特に対応不要です :ok_man: ）

2024-04-16 01:38 UTC, darmadevZone commented
[.github/actions/workflows/を.github/workflowsへ移動](https://github.com/darmadevZone/android-practice/pull/32/commits/4094cc0e7f2ae139123da64f9757f7634f6ee745)を修正したので確認お願いします

2024-04-16 02:44 UTC, askldfghj commented on .github/actions/workflows/Dangerfile
@darmadevZone 
対応ありがとうございます。
確認できました。

2024-04-16 02:45 UTC, askldfghj approved these changes
LGTM

2024-04-16 05:58 UTC, merged